### ISSUE TITLE
Umbrella for initial release

### ISSUE THREAD

**Issue by Aftabnack** [Aftabnack/starterify#1]
# List of features

> Basic

* [ ] (Config) Ability to download whole repos as starter-kit
* [ ] List of starter-kits
* [ ] `npm init` cli

> Next steps

* [ ] (Config) Ability to override deps, devDeps, scripts
* [ ] (Config) Ability to use releases/tags for downloading repos
* [ ] (Config) Ability to download sub dir as a template

> Later

* [ ] (Config) Extensions for starter kit
